name: "Code scanning"

on:
  workflow_call:
    inputs:
      gosec-args:
        description: "Arguments passed to 'gosec' - see: https://github.com/securego/gosec/blob/HEAD/README.md#usage"
        default: "-fmt sarif -out results.sarif -no-fail ./..."
        type: string

jobs:
  gosec:
    name: Go Security Checker
    runs-on: large_runner
    container:
      image: securego/gosec:2.22.1 # needs to be set as the securego/gosec@v2.22.1 uses the securego/gosec:2.22.0 image
    permissions:
      # Required to upload SARIF files
      security-events: write
      # for actions/checkout to fetch code
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run Gosec Security Scanner
        # need to set @master as the action always uses the last but not least version
        # e.g. securego/gosec@v2.22.1 uses the securego/gosec:2.22.0 image
        # but we require support for go 1.24 which comes with 2.22.1
        uses: securego/gosec@master
        with:
          args: "${{ inputs.gosec-args }}"
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@17a820bf2e43b47be2c72b39cc905417bc1ab6d0 # v3.28.6
        with:
          sarif_file: results.sarif
