name: Auto Add Issue Labels
on:
  issues:
    types:
      - opened

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add default Labels to new issues
        uses: actions/github-script@v7
        with:
          script: |
            const labelsToAdd = ['needs/validation', 'needs/refinement'];
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: context.issue.number,
              labels: labelsToAdd
            });
